const shopItemsData = [
    {
        id: 1,
        name: 'Panda',
        price: 10,
        description: 'This is item 1',
        image: 'https://via.placeholder.com/150',
        quantity: 1,
    },
    {
        id: 2,
        name: 'Pizza',
        price: 20,
        description: 'This is item 2',
        image: 'https://via.placeholder.com/150',
        quantity: 1,
    },
    {
        id: 3,
        name: 'Violin',
        price: 30,
        description: 'This is item 3',
        image: 'https://via.placeholder.com/150',
        quantity: 1,
    },
    {
        id: 4,
        name: 'Item 4',
        price: 40,
        description: 'This is item 4',
        image: 'https://via.placeholder.com/150',
        quantity: 1,
    },
    {
        id: 5,
        name: 'Item 5',
        price: 50,
        description: 'This is item 5',
        image: 'https://via.placeholder.com/150',
        quantity: 1,
    },
    {
        id: 6,
        name: 'Item 6',
        price: 600,
        description: 'This is item 6',
        image: 'https://via.placeholder.com/150',
        quantity: 1,
    },
    {
        id: 7,
        name: 'Item 7',
        price: 70,
        description: 'This is item 7',
        image: 'https://via.placeholder.com/150',
        quantity: 1,
    },
    {
        id: 8,
        name: 'Item 8',
        price: 80,
        description: 'This is item 8',
        image: 'https://via.placeholder.com/150',
        quantity: 1,
    },
    {
        id: 9,
        name: 'Item 9',
        price: 90,
        description: 'This is item 9',
        image: 'https://via.placeholder.com/150',
        quantity: 1,
    },
    {
        id: 10,
        name: 'Item 10',
        price: 100,
        description: 'This is item 10',
        image: 'https://via.placeholder.com/150',
        quantity: 1,
    },
];
export default shopItemsData;
