export type Piece = {
    id: string;
    leadSheet: string;
    meter: string;
    key: string;
    tempo: string;
    title: string;
    composer: string;
    arranger: string;
    lyricist: string;
    lyrics: string;
    album: string;
    artist: string;
    year: string;
    genre: string;
    duration: string;
    instruments: string[];
    tags: string[];
    description: string;
};